# Twilio voor SMS-bevestigingen
TWILIO_SID = "AC006a6ab61298ec3eb41163b045d7d746"
TWILIO_TOKEN = "1e64c88272867e2cbe3aa6c56bbb6f6e"
TWILIO_PHONE = "+3197010288263"

# App basis
COMPANY_NAME = "D'or Booking System"
ADMIN_PASSWORD = "vuren2025"

# Stripe voor betalingen (testmodus)
STRIPE_SECRET_KEY = "sk_test_51..."sk_test_51SP08OD1KZUWdI6iaVB9NlaiTY4t5ftC4cejLoed63Fql6FxDpUcZq1gqTJxrdeyOrDbOZW4aJZBFatbR9lohZr100v4P8lEnV"
STRIPE_PUBLISHABLE_KEY = "pk_test_51..."pk_test_51SP08OD1KZUWdI6iGFFeZuz6zlX595KIPjk7Z4ltrCXA5x2tDmGhJqPHugYlLBMkvdXTJ5bXLj0xHkfQOb8EWVWB008Uxzo7jR"
STRIPE_PRICE_ID = "price_1..."price_1SP0j5D1KZUWdI6iZiODSYeO"
