TWILIO_SID = "AC006a6ab61298ec3eb41163b045d7d746"
TWILIO_TOKEN = "1e64c88272867e2cbe3aa6c56bbb6f6e"
TWILIO_PHONE = "+3197010288263"
COMPANY_NAME = "D'or Booking System"
ADMIN_PASSWORD = "vuren2025"
STRIPE_PUBLISHABLE_KEY = "pk_test_..."
STRIPE_SECRET_KEY = "sk_test_..."
STRIPE_PRODUCT_ID = "prod_..."  # Maak een product in Stripe voor abonnement
