# ✅ Stripe Configuratie
STRIPE_SECRET_KEY = "sk_test_51SP08OD1KZUWdI6i7FWevGmlZ48B8xdM0csnKNatwD2vM6xJaFz3JJpAR6aNKZizVU4GWoOYmTGfpJycgGJdznB300GXPbLZY9"
STRIPE_PRICE_ID = "price_1SPTMzD1KZUWdI6i7Vncr6FH"
APP_URL = "https://d-or-booking-system-gwbucvc56tnfubjkhgzsqn.streamlit.app"

# ✅ Twilio Configuratie (voor sms)
TWILIO_SID = "AC006a6ab61298ec3eb41163b045d7d746"
TWILIO_TOKEN = "1e64c88272867e2cbe3aa6c56bbb6f6e"
TWILIO_PHONE = "+3197010288263"
TWILIO_WHATSAPP_FROM = "whatsapp:+14155238886"

# ✅ App instellingen
COMPANY_NAME = "D'or Booking System"
ADMIN_PASSWORD = "vuren2025"
