TWILIO_SID = "AC006a6ab61298ec3eb41163b045d7d746"
TWILIO_TOKEN = "1e64c88272867e2cbe3aa6c56bbb6f6e"
TWILIO_PHONE = "+3197010288263"

COMPANY_NAME = "D'or Booking System"
ADMIN_PASSWORD = "vuren2025"

STRIPE_SECRET_KEY = "sk_test_51SP800D1KZUMd1617VEwGm1Z48B8xdM0 csnKNatwD2vM6xJaFz3JJpAR6aNKZi zVU4GNooYmTG fpJycgG3dznB300GXPbLZY9"
STRIPE_PUBLISHABLE_KEY = "pk_test_51SP08OD1KZUWdI6iGFFeZuz6zlX595KIPjk7Z4ltrCXA5x2tDmGhJqPHugYlLBMkvdXTJ5bXLj0xHkfQOb8EWVWB008Uxzo7jR"
STRIPE_PRICE_ID = "price_1SP8j501KZUMdI61Z1ODSYe0"

APP_URL = "https://d-or-booking-system-gwbucvc56tnfubjkhgzsqn.streamlit.app"
