# .streamlit/config.toml

[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 8501
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[theme]
base = "light"
primaryColor = "#D4AF37"            # Dâ€™or goud
backgroundColor = "#FFFFFF"         # wit
secondaryBackgroundColor = "#F7F7F9"# zachte kaart
textColor = "#1A1A1A"               # bijna-zwart
font = "sans serif"
