# ===== Stripe =====
STRIPE_SECRET_KEY = "rk_test_51SP08OD1KZUWdI6ix1KNj8zajuBEss8zBkwjBrfIWbAvPnKfznHOtQKgtT4rHzneZ2jL6N1rCr7nAGjWfFkdjxFQ00eSZVVVdE"
STRIPE_PRICE_ID   = "prod_TLi9jgUpWETFO7"   # zie stap 2 hieronder

# ===== Twilio =====
TWILIO_SID           = "AC006a6ab61298ec3eb41163b045dd74f6"
TWILIO_TOKEN         = "e543aa07f060bb2abec683e8eb986dbc"
TWILIO_PHONE         = "+3197010288263"
TWILIO_WHATSAPP_FROM = "whatsapp:+14155238886"

# ===== App =====
APP_URL        = "https://d-or-booking-system-....streamlit.app"
COMPANY_NAME   = "D'or Booking System"
ADMIN_PASSWORD = "sterk-wachtwoord"
TEST_SMS_TO    = "+3197010288263"
